# Generated by Django 4.2.11 on 2024-04-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
