# Generated by Django 4.2.11 on 2024-04-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author_comment_author_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
